### ISSUE TITLE
Is this exact NLTK version (2.09b) strictly necessary?

### ISSUE THREAD

**Issue by alexeyev** [habernal/feng-hirst-rst-parser-acl-2014#3]
Thank you for the great tool!

Can one use a fresher version of NLTK? Or it would just mean that the original behaviour is not guaranteed?

Best regards.

**Comment by alexeyev** [comment]
Oh, sorry for the disturbance, here's the answer

` April 20, 2013: It seems that newer version of NLTK has a different interface for its tree objects. Our  implementation was based on NLTK 2.0b9. So if you're experiencing with errors reported such as "'function' object has no attribute 'parent'", please either replace your NLTK version with 2.0b9, or go through the source codes under src/ folder, adding brackets to all *.parent, *.left_sibling, *.right_sibling, *.root, *.treepos, *.treepositions. (e.g., *.parent becomes *.parent()).`

http://www.cs.toronto.edu/~weifeng/software.html

**Comment by habernal** [comment]
Glad you found the solution :)
